Add new wrappers and fix cxt issues
blambo/qq pull request #1
Opened 2017-06-15 05:07 UTC by jaichopra

2017-06-15 07:40 UTC, blambo requested changes

2017-06-15 07:40 UTC, blambo commented on qq.coffee
> +  spread: (fulfilled, rejected) => @promise.spread fulfilled, rejected
We still need this one wrapped in the promise context

2017-06-18 22:55 UTC, jaichopra commented
Added new commit

2017-06-19 05:13 UTC, blambo approved these changes
LGTM

2017-06-29 03:51 UTC, blambo requested changes

2017-06-29 03:51 UTC, blambo commented on qq.coffee
> +
Let's remove the commented out code

2017-07-10 05:11 UTC, jaichopra commented on qq.coffee
> +
These have been removed in the latest commit

2017-07-10 23:42 UTC, blambo commented
LGTM

2017-07-10 23:43 UTC, merged